"""
Kafka Producer for Data Center Telemetry Simulator.

Publishes TelemetryRecord objects generated by DataCenterSimulator
to Apache Kafka topics with server_id as the message key.
"""

import argparse
import os
import sys
import time
from typing import List, Optional, Any

# Ensure parent directory is in sys.path for direct script execution
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from producer.models import TelemetryRecord
from producer.server_config import SimulationConfig
from producer.simulator import DataCenterSimulator


class KafkaTelemetryProducer:
    """
    Publishes TelemetryRecord objects to Apache Kafka.
    
    Uses server_id as the Kafka message key for consistent partition routing.
    Serializes TelemetryRecord objects to UTF-8 JSON bytes.
    """

    def __init__(
        self,
        bootstrap_servers: str = "localhost:9092",
        topic: str = "server_telemetry",
        producer_instance: Optional[Any] = None,
    ):
        self.bootstrap_servers = bootstrap_servers
        self.topic = topic
        self.producer = producer_instance

    def connect(self) -> None:
        """Establish connection to Kafka broker."""
        if self.producer is not None:
            return

        try:
            from kafka import KafkaProducer
            self.producer = KafkaProducer(
                bootstrap_servers=self.bootstrap_servers,
                request_timeout_ms=1000,
                max_block_ms=1000,
                retries=1,
            )
        except Exception as e:
            raise ConnectionError(
                f"Unable to connect to Kafka at {self.bootstrap_servers}: {e}"
            ) from e

    def send(self, record: TelemetryRecord, sync: bool = True, timeout: float = 10.0) -> Any:
        """
        Send a TelemetryRecord to the configured Kafka topic.
        
        Args:
            record: TelemetryRecord object to send.
            sync: If True, blocks until metadata acknowledgement is received.
            timeout: Max time in seconds to wait for acknowledgement if sync=True.

        Returns:
            RecordMetadata if sync=True, or FutureRecordMetadata if sync=False.
        """
        if self.producer is None:
            self.connect()

        try:
            key_bytes = record.server_id.encode("utf-8")
            value_bytes = record.to_json().encode("utf-8")
            future = self.producer.send(self.topic, key=key_bytes, value=value_bytes)
            if sync:
                metadata = future.get(timeout=timeout)
                return metadata
            return future
        except Exception as e:
            raise RuntimeError(f"Failed to send record for server {record.server_id} to topic {self.topic}: {e}") from e

    def send_batch(self, records: List[TelemetryRecord], sync: bool = True, timeout: float = 10.0) -> List[Any]:
        """Send a list of TelemetryRecord objects to Kafka."""
        results = []
        for record in records:
            res = self.send(record, sync=sync, timeout=timeout)
            results.append(res)
        return results

    def flush(self) -> None:
        """Flush pending messages."""
        if self.producer is not None:
            self.producer.flush()

    def close(self) -> None:
        """Close the Kafka producer cleanly."""
        if self.producer is not None:
            self.producer.close()
            self.producer = None


def parse_args(args_list: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Data Center Telemetry Kafka Producer CLI"
    )
    parser.add_argument(
        "--bootstrap-server",
        type=str,
        default="localhost:9092",
        help="Kafka broker bootstrap server (default: localhost:9092).",
    )
    parser.add_argument(
        "--topic",
        type=str,
        default="server_telemetry",
        help="Target Kafka topic (default: server_telemetry).",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run in finite test mode without continuous sleeping.",
    )
    parser.add_argument(
        "--records",
        type=int,
        default=20,
        help="Number of telemetry events to generate and send in test mode (default: 20).",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=5.0,
        help="Telemetry interval in seconds for continuous mode (default: 5.0).",
    )
    parser.add_argument(
        "--racks",
        type=int,
        default=5,
        help="Number of racks in topology (default: 5).",
    )
    parser.add_argument(
        "--servers-per-rack",
        type=int,
        default=4,
        help="Number of servers per rack (default: 4).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Optional random seed for reproducible simulation.",
    )
    parser.add_argument(
        "--disable-incidents",
        action="store_true",
        help="Disable automatic random incident generation.",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        choices=[
            "normal",
            "cpu_overload",
            "overheating",
            "disk_saturation",
            "network_congestion",
            "memory_pressure",
        ],
        default=None,
        help="Inject a specific incident scenario deterministically.",
    )
    return parser.parse_args(args_list)


def main() -> None:
    args = parse_args()

    config = SimulationConfig(
        num_racks=args.racks,
        servers_per_rack=args.servers_per_rack,
        telemetry_interval=args.interval,
        enable_incidents=not args.disable_incidents,
    )

    simulator = DataCenterSimulator(
        config=config, seed=args.seed, scenario=args.scenario
    )

    producer = KafkaTelemetryProducer(
        bootstrap_servers=args.bootstrap_server,
        topic=args.topic,
    )

    try:
        producer.connect()
    except Exception as e:
        print(f"Error: Unable to connect to Kafka at {args.bootstrap_server}")
        print(f"Details: {e}")
        sys.exit(1)

    try:
        if args.test:
            # Test Mode: finite number of events sent to Kafka
            records_emitted = 0
            while records_emitted < args.records:
                step_records = simulator.generate_step()
                for record in step_records:
                    metadata = producer.send(record, sync=True)
                    print(
                        f"Sent: server={record.server_id} "
                        f"topic={metadata.topic} "
                        f"partition={metadata.partition} "
                        f"offset={metadata.offset}"
                    )
                    sys.stdout.flush()
                    records_emitted += 1
                    if records_emitted >= args.records:
                        break
            producer.flush()
            producer.close()
            print(f"Successfully published {records_emitted} records to Kafka.")
        else:
            # Continuous Mode
            print(f"Starting continuous telemetry streaming to {args.topic} at {args.bootstrap_server}...")
            print(f"Topology: {config.num_racks} racks x {config.servers_per_rack} servers ({config.num_racks * config.servers_per_rack} servers total)")
            print(f"Interval: {config.telemetry_interval}s. Press Ctrl+C to stop.")
            while True:
                step_records = simulator.generate_step()
                for record in step_records:
                    metadata = producer.send(record, sync=True)
                    print(
                        f"Sent: server={record.server_id} "
                        f"topic={metadata.topic} "
                        f"partition={metadata.partition} "
                        f"offset={metadata.offset}"
                    )
                    sys.stdout.flush()
                time.sleep(config.telemetry_interval)
    except KeyboardInterrupt:
        print("\nShutdown signal received (Ctrl+C). Flushing pending messages...")
    except Exception as e:
        print(f"Error publishing to Kafka: {e}")
        sys.exit(1)
    finally:
        producer.flush()
        producer.close()


if __name__ == "__main__":
    main()
