"""
Kafka Producer for Data Center Telemetry Simulator.

Publishes TelemetryRecord objects generated by DataCenterSimulator
to Apache Kafka topics with server_id as the message key.
"""

import argparse
import os
import sys
import time
from typing import List, Optional, Any

# Ensure parent directory is in sys.path for direct script execution
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from producer.models import TelemetryRecord
from producer.server_config import SimulationConfig, calculate_server_shard
from producer.simulator import DataCenterSimulator


class KafkaTelemetryProducer:
    """
    Publishes TelemetryRecord objects to Apache Kafka.
    
    Uses server_id as the Kafka message key for consistent partition routing.
    Serializes TelemetryRecord objects to UTF-8 JSON bytes.
    """

    def __init__(
        self,
        bootstrap_servers: str = "localhost:9092",
        topic: str = "server_telemetry",
        producer_instance: Optional[Any] = None,
    ):
        self.bootstrap_servers = bootstrap_servers
        self.topic = topic
        self.producer = producer_instance

    def connect(self, max_retries: int = 1, retry_interval: float = 3.0) -> None:
        """
        Establish connection to Kafka broker, with configurable retries and backoff.
        
        Args:
            max_retries: Maximum number of connection attempts before failing.
            retry_interval: Time in seconds between connection retries.
        """
        if self.producer is not None:
            return

        attempt = 0
        while True:
            try:
                from kafka import KafkaProducer
                self.producer = KafkaProducer(
                    bootstrap_servers=self.bootstrap_servers,
                    request_timeout_ms=3000,
                    max_block_ms=3000,
                    retries=1,
                )
                print(f"Connected to Kafka broker at {self.bootstrap_servers}")
                return
            except Exception as e:
                attempt += 1
                if attempt >= max_retries:
                    raise ConnectionError(
                        f"Unable to connect to Kafka at {self.bootstrap_servers}: {e}"
                    ) from e
                print(
                    f"Waiting for Kafka broker at {self.bootstrap_servers} "
                    f"(attempt {attempt}/{max_retries})... {e}"
                )
                time.sleep(retry_interval)

    def send(self, record: TelemetryRecord, sync: bool = True, timeout: float = 10.0) -> Any:
        """
        Send a TelemetryRecord to the configured Kafka topic.
        
        Args:
            record: TelemetryRecord object to send.
            sync: If True, blocks until metadata acknowledgement is received.
            timeout: Max time in seconds to wait for acknowledgement if sync=True.

        Returns:
            RecordMetadata if sync=True, or FutureRecordMetadata if sync=False.
        """
        if self.producer is None:
            self.connect()

        try:
            key_bytes = record.server_id.encode("utf-8")
            value_bytes = record.to_json().encode("utf-8")
            future = self.producer.send(self.topic, key=key_bytes, value=value_bytes)
            if sync:
                metadata = future.get(timeout=timeout)
                return metadata
            return future
        except Exception as e:
            raise RuntimeError(f"Failed to send record for server {record.server_id} to topic {self.topic}: {e}") from e

    def send_batch(self, records: List[TelemetryRecord], sync: bool = True, timeout: float = 10.0) -> List[Any]:
        """Send a list of TelemetryRecord objects to Kafka."""
        results = []
        for record in records:
            res = self.send(record, sync=sync, timeout=timeout)
            results.append(res)
        return results

    def flush(self) -> None:
        """Flush pending messages."""
        if self.producer is not None:
            self.producer.flush()

    def close(self) -> None:
        """Close the Kafka producer cleanly."""
        if self.producer is not None:
            self.producer.close()
            self.producer = None


def parse_args(args_list: Optional[List[str]] = None) -> argparse.Namespace:
    env_bootstrap = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
    env_topic = os.getenv("KAFKA_TOPIC", "server_telemetry")
    env_interval = float(os.getenv("TELEMETRY_INTERVAL", "5.0"))
    env_racks = int(os.getenv("NUM_RACKS", "5"))
    env_servers = int(os.getenv("SERVERS_PER_RACK", "4"))
    env_incidents = os.getenv("ENABLE_INCIDENTS", "true").lower() in ("true", "1", "yes")
    env_scenario = os.getenv("SCENARIO", None)
    env_seed = int(os.getenv("SEED")) if os.getenv("SEED") else None
    env_test = os.getenv("TEST_MODE", "false").lower() in ("true", "1", "yes")
    env_records = int(os.getenv("RECORDS_COUNT", "20"))

    # Sharding environment variables
    env_start_idx = int(os.getenv("SERVER_START_INDEX")) if os.getenv("SERVER_START_INDEX") else None
    env_end_idx = int(os.getenv("SERVER_END_INDEX")) if os.getenv("SERVER_END_INDEX") else None
    env_shard_idx = int(os.getenv("SHARD_INDEX")) if os.getenv("SHARD_INDEX") else None
    env_total_shards = int(os.getenv("TOTAL_SHARDS")) if os.getenv("TOTAL_SHARDS") else None

    # Hostname / Pod name ordinal fallback for StatefulSet or Kubernetes pods (e.g. telemetry-simulator-1)
    pod_name = os.getenv("POD_NAME", os.getenv("HOSTNAME", ""))
    if env_shard_idx is None and "-" in pod_name:
        parts = pod_name.split("-")
        if parts[-1].isdigit():
            env_shard_idx = int(parts[-1])

    parser = argparse.ArgumentParser(
        description="Data Center Telemetry Kafka Producer CLI"
    )
    parser.add_argument(
        "--bootstrap-server",
        type=str,
        default=env_bootstrap,
        help=f"Kafka broker bootstrap server (default: {env_bootstrap}).",
    )
    parser.add_argument(
        "--topic",
        type=str,
        default=env_topic,
        help=f"Target Kafka topic (default: {env_topic}).",
    )
    parser.add_argument(
        "--test",
        action="store_true",
        default=env_test,
        help="Run in finite test mode without continuous sleeping.",
    )
    parser.add_argument(
        "--records",
        type=int,
        default=env_records,
        help=f"Number of telemetry events to generate and send in test mode (default: {env_records}).",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=env_interval,
        help=f"Telemetry interval in seconds for continuous mode (default: {env_interval}).",
    )
    parser.add_argument(
        "--racks",
        type=int,
        default=env_racks,
        help=f"Number of racks in topology (default: {env_racks}).",
    )
    parser.add_argument(
        "--servers-per-rack",
        type=int,
        default=env_servers,
        help=f"Number of servers per rack (default: {env_servers}).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=env_seed,
        help="Optional random seed for reproducible simulation.",
    )
    parser.add_argument(
        "--disable-incidents",
        action="store_true",
        default=not env_incidents,
        help="Disable automatic random incident generation.",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        choices=[
            "normal",
            "cpu_overload",
            "overheating",
            "disk_saturation",
            "network_congestion",
            "memory_pressure",
        ],
        default=env_scenario,
        help="Inject a specific incident scenario deterministically.",
    )
    parser.add_argument(
        "--shard-index",
        type=int,
        default=env_shard_idx,
        help="0-based shard index for replica server partitioning.",
    )
    parser.add_argument(
        "--total-shards",
        type=int,
        default=env_total_shards,
        help="Total number of replica shards.",
    )
    parser.add_argument(
        "--server-start-index",
        type=int,
        default=env_start_idx,
        help="Explicit 1-based start server ID for sharding.",
    )
    parser.add_argument(
        "--server-end-index",
        type=int,
        default=env_end_idx,
        help="Explicit 1-based end server ID for sharding.",
    )
    return parser.parse_args(args_list)


def main() -> None:
    args = parse_args()

    start_idx = args.server_start_index
    end_idx = args.server_end_index

    if (start_idx is None or end_idx is None) and (args.shard_index is not None and args.total_shards is not None):
        total_servers = args.racks * args.servers_per_rack
        start_idx, end_idx = calculate_server_shard(total_servers, args.shard_index, args.total_shards)

    config = SimulationConfig(
        num_racks=args.racks,
        servers_per_rack=args.servers_per_rack,
        telemetry_interval=args.interval,
        enable_incidents=not args.disable_incidents,
        server_start_index=start_idx,
        server_end_index=end_idx,
    )

    simulator = DataCenterSimulator(
        config=config, seed=args.seed, scenario=args.scenario
    )

    producer = KafkaTelemetryProducer(
        bootstrap_servers=args.bootstrap_server,
        topic=args.topic,
    )

    max_retries = int(os.getenv("KAFKA_CONNECT_RETRIES", "10"))
    retry_interval = float(os.getenv("KAFKA_CONNECT_RETRY_INTERVAL", "3.0"))

    try:
        producer.connect(max_retries=max_retries, retry_interval=retry_interval)
    except Exception as e:
        print(f"Error: Unable to connect to Kafka at {args.bootstrap_server}")
        print(f"Details: {e}")
        sys.exit(1)

    try:
        if args.test:
            # Test Mode: finite number of events sent to Kafka
            records_emitted = 0
            while records_emitted < args.records:
                step_records = simulator.generate_step()
                for record in step_records:
                    metadata = producer.send(record, sync=True)
                    print(
                        f"Sent: server={record.server_id} "
                        f"topic={metadata.topic} "
                        f"partition={metadata.partition} "
                        f"offset={metadata.offset}"
                    )
                    sys.stdout.flush()
                    records_emitted += 1
                    if records_emitted >= args.records:
                        break
            producer.flush()
            producer.close()
            print(f"Successfully published {records_emitted} records to Kafka.")
        else:
            # Continuous Mode
            print(f"Starting continuous telemetry streaming to {args.topic} at {args.bootstrap_server}...")
            assigned_count = len(simulator.servers)
            start_str = f"SRV{config.server_start_index:03d}" if config.server_start_index else "SRV001"
            end_str = f"SRV{config.server_end_index:03d}" if config.server_end_index else f"SRV{config.total_servers:03d}"
            print(f"Assigned Shard: {start_str}..{end_str} ({assigned_count} servers assigned)")
            print(f"Interval: {config.telemetry_interval}s. Press Ctrl+C to stop.")
            while True:
                step_records = simulator.generate_step()
                for record in step_records:
                    metadata = producer.send(record, sync=True)
                    print(
                        f"Sent: server={record.server_id} "
                        f"topic={metadata.topic} "
                        f"partition={metadata.partition} "
                        f"offset={metadata.offset}"
                    )
                    sys.stdout.flush()
                time.sleep(config.telemetry_interval)
    except KeyboardInterrupt:
        print("\nShutdown signal received (Ctrl+C). Flushing pending messages...")
    except Exception as e:
        print(f"Error publishing to Kafka: {e}")
        sys.exit(1)
    finally:
        producer.flush()
        producer.close()


if __name__ == "__main__":
    main()
