apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: data-center-monitoring
  labels:
    app: telemetry-simulator
    app.kubernetes.io/part-of: data-center-monitoring
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.data-center-monitoring.svc.cluster.local:9092"
  KAFKA_TOPIC: "server_telemetry"
  TELEMETRY_INTERVAL: "5.0"
  NUM_RACKS: "5"
  SERVERS_PER_RACK: "4"
  ENABLE_INCIDENTS: "true"
  TOTAL_SHARDS: "1"
  KAFKA_CONNECT_RETRIES: "15"
  KAFKA_CONNECT_RETRY_INTERVAL: "3.0"
