apiVersion: v1
kind: Service
metadata:
  name: telemetry-simulator-service
  namespace: data-center-monitoring
  labels:
    app: telemetry-simulator
    app.kubernetes.io/part-of: data-center-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: telemetry-simulator
